import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

GPU_USAGE_THRESHOLD = 10 # %
CPU_USAGE_THRESHOLD = 10 # %
RAM_USAGE_THRESHOLD = 10 # %
FULL_DISK_USAGE_THRESHOLD = 97 # %
IDLE_DISK_USAGE_THRESHOLD = 3 # %
TIME_LIMIT = 2 # hours

ADMIN_CHECKING_HOUR = 0
ADMIN_CHECKING_MINUTE = 5
ADMIN_CHECKING_SECOND = 0

TOKEN_EXPIRED_TIME_DAYS = 7
TOKEN_EXPIRED_TIME_HOURS = 0
TOKEN_EXPIRED_TIME_MINUTES = 0

